FROM alpine:3.18 as builder

ARG TARGETARCH

RUN apk add --no-cache \
    g++ \
    make

WORKDIR /src
COPY ./src/hello.cc .

RUN g++ hello.cc -o hello

FROM alpine:3.18

ARG TARGETARCH

LABEL maintainer="Leonardo Held" \
      description="Multiarch Docker image with Hello World (Alpine)" \
      architecture="$TARGETARCH"

COPY --from=builder /src/hello /usr/local/bin/hello

ENTRYPOINT ["/usr/local/bin/hello"]
