FROM debian:bookworm-slim as builder

ARG TARGETPLATFORM
ARG TARGETARCH

RUN apt-get update && apt-get install -y \
    build-essential \
    make

WORKDIR /src
COPY ./src/hello.cc .

RUN gcc hello.cc -o hello

FROM debian:bookworm

ARG TARGETARCH

LABEL maintainer="Leonardo Held" \
      description="Multiarch Docker image with Hello World" \
      architecture="$TARGETARCH"

COPY --from=builder /src/hello /usr/local/bin/hello

ENTRYPOINT ["/usr/local/bin/hello"]
