name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Debian Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.debian
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/myapp-debian:latest

      - name: Build and Push Alpine Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.alpine
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/myapp-alpine:latest

      - name: Build and Push Distroless Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.distroless
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/myapp-distroless:latest

